spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post_db
    username: postgres
    password: Akkiwat5900
    # Additional properties if needed

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        # Set to true to enable SQL logging, for example
        format_sql: true # Set to true to format SQL queries, for example
server:
  port: 8081